SELECT CEIL(39.29)FROM DUAL;
SELECT CEIL(-39.9)FROM DUAL;
SELECT CEIL(39/3)FROM DUAL;
SELECT FLOOR(39.76)FROM DUAL;
SELECT FLOOR(-39.3)FROM DUAL;
SELECT FLOOR(39/4)FROM DUAL;
SELECT SQRT(39)FROM DUAL;
SELECT SQRT(2)FROM DUAL;
SELECT ABS(39.29)FROM DUAL;
SELECT ABS(-39.14) FROM DUAL;
SELECT ABS(-39) FROM DUAL;
SELECT SYSDATE AS NOW FROM DUAL;
SELECT SYSTIMESTAMP FROM DUAL;
SELECT LEAST('Hi','Hello','kevin')FROM DUAL;
SELECT GREATEST('Hi','Hello','kevin')FROM DUAL;
SELECT LTRIM('Trim me')FROM DUAL;
SELECT RTRIM(' I love India')FROM DUAL;

SELECT RPAD('KEVIN',15,'/') FROM DUAL;
SELECT RPAD(123,6,'0') FROM DUAL;
SELECT REVERSE('uoyerawoholleh') FROM DUAL;
SELECT TO_CHAR('palindrome') FROM DUAL
WHERE 'racecar'= REVERSE('racecar');
SELECT LENGTH('Oracle Database') FROM DUAL;
select concat(concat(concat(concat('oracle', ' '),
'sql'), ' '), concat(concat('is', ' '),
concat('powerful', ' flexible'))) from dual;
SELECT CONCAT('kevin','biju') FROM DUAL;
SELECT SUBSTR('India is my country', 6, 3) FROM DUAL;
SELECT SUBSTR('kevin', LENGTH('kevin') / 2 , 3)
FROM DUAL;
SELECT SUBSTR('Substring', 1, 3) FROM DUAL;
commit;
